# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"no_emp_dim": "00_core.ipynb",
         "maybe_unsqueeze": "00_core.ipynb",
         "show_array": "00_core.ipynb",
         "TSeries": "00_core.ipynb",
         "URLs.UCR": "00_core.ipynb",
         "get_ucr": "00_core.ipynb",
         "load_df_ucr": "00_core.ipynb",
         "get_x": "00_core.ipynb",
         "get_y": "00_core.ipynb",
         "AdaptiveConcatPool1d": "02_models.inception.ipynb",
         "conv": "02_models.inception.ipynb",
         "act_fn": "02_models.inception.ipynb",
         "Shortcut": "02_models.inception.ipynb",
         "InceptionModule": "02_models.inception.ipynb",
         "create_inception": "02_models.inception.ipynb"}

modules = ["core.py",
           "models/inception.py"]

doc_url = "https://tcapelle.github.io/timeseries_fastai/"

git_url = "https://github.com/tcapelle/timeseries_fastai/tree/master/"

def custom_doc_links(name): return None
