# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"no_emp_dim": "00_core.ipynb",
         "maybe_unsqueeze": "00_core.ipynb",
         "show_array": "00_core.ipynb",
         "TSeries": "00_core.ipynb",
         "URLs.UCR": "00_core.ipynb",
         "get_ucr": "00_core.ipynb",
         "load_df_ucr": "00_core.ipynb",
         "get_x": "00_core.ipynb",
         "get_y": "00_core.ipynb",
         "TSBlock": "01_data.ipynb",
         "TSDataLoaders": "01_data.ipynb",
         "stack_train_valid": "01_data.ipynb",
         "act_fn": "02_models.ipynb",
         "AdaptiveConcatPool1d": "02_models.ipynb",
         "create_mlp": "02_models.ipynb",
         "create_fcn": "02_models.ipynb",
         "res_block_1d": "02_models.ipynb",
         "create_resnet": "02_models.ipynb",
         "Shortcut": "02_models.ipynb",
         "conv": "02_models.ipynb",
         "InceptionModule": "02_models.ipynb",
         "create_inception": "02_models.ipynb"}

modules = ["core.py",
           "data.py",
           "models.py"]

doc_url = "https://tcapelle.github.io/timeseries_fastai/"

git_url = "https://github.com/tcapelle/timeseries_fastai/tree/master/"

def custom_doc_links(name): return None
